import { Figtree } from 'next/font/google'
import './globals.css'
import Header from '../ui/header'

const figtree = Figtree({
    variable: '--font-figtree',
    subsets: ['latin'],
})

export const metadata = {
    title: 'Jedel Jardem App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                style={{ fontFamily: 'Figtree, sans-serif' }}
                className={`${figtree.variable} antialiased`}
            >
                <Header />
                {children}
            </body>
        </html>
    )
}
